# Generated by Django 5.1.15 on 2026-04-07 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('department', 'Department'), ('team', 'Team'), ('workspace', 'Workspace')], default='department', max_length=20)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='orgs.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_processes', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_processes', to='orgs.department')),
            ],
            options={
                'db_table': 'process',
            },
        ),
        migrations.CreateModel(
            name='ProcessVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('content_md', models.TextField()),
                ('frontmatter_yaml', models.TextField(blank=True, default='')),
                ('change_summary', models.CharField(blank=True, default='', max_length=500)),
                ('authored_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_versions', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='processes.process')),
            ],
            options={
                'db_table': 'process_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='process',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='processes.processversion'),
        ),
        migrations.AddIndex(
            model_name='processversion',
            index=models.Index(fields=['process', '-version_number'], name='idx_version_latest'),
        ),
        migrations.AddConstraint(
            model_name='processversion',
            constraint=models.UniqueConstraint(fields=('process', 'version_number'), name='uq_version_process_number'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['department', 'status'], name='idx_process_dept_status'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['status', '-updated_at'], name='idx_process_status_updated'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['slug'], name='idx_process_slug'),
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(fields=('department', 'slug'), name='uq_process_dept_slug'),
        ),
    ]
