# Generated by Django 5.1.15 on 2026-04-16 06:06

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('processes', '0002_versionfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.RemoveIndex(
            model_name='versionfile',
            name='idx_vfile_version_path',
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['-updated_at'], name='idx_process_updated_at'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'description'], name='idx_process_search_trgm', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(condition=models.Q(('visibility__in', ['team', 'workspace'])), fields=['visibility'], name='idx_process_visibility'),
        ),
    ]
