# Generated by Django 5.1.15 on 2026-04-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_remove_versionfile_idx_vfile_version_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processversion',
            name='koinoflow_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
