# Generated by Django 5.1.15 on 2026-04-07 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('confluence', 'Confluence')], max_length=50)),
                ('cloud_id', models.CharField(blank=True, max_length=100)),
                ('site_url', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('webhook_id', models.CharField(blank=True, max_length=100)),
                ('allowed_spaces', models.JSONField(blank=True, default=list, help_text='Space keys to sync. Empty list means all spaces.')),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_credentials', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_credentials', to='orgs.workspace')),
            ],
            options={
                'db_table': 'connector_credential',
            },
        ),
        migrations.CreateModel(
            name='CaptureCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content_md', models.TextField()),
                ('frontmatter_yaml', models.TextField(blank=True)),
                ('probability_score', models.FloatField(default=0.0)),
                ('automation_tier', models.CharField(choices=[('ready', 'Ready to automate'), ('needs_integration', 'Needs integration'), ('manual_only', 'Manual only')], default='manual_only', max_length=20)),
                ('automation_reasoning', models.TextField(blank=True)),
                ('integration_needs', models.JSONField(default=list)),
                ('grounding_sources', models.JSONField(blank=True, default=list, help_text='Web sources cited by the LLM during grounded extraction (uri, title).')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('promoted', 'Promoted to process'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('promoted_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_candidates', to='processes.process')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_candidates', to='connectors.connectorcredential')),
            ],
            options={
                'db_table': 'capture_candidate',
            },
        ),
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pages_scored', models.PositiveIntegerField(default=0)),
                ('pages_extracted', models.PositiveIntegerField(default=0)),
                ('candidates_created', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='connectors.connectorcredential')),
            ],
            options={
                'db_table': 'extraction_job',
            },
        ),
        migrations.CreateModel(
            name='SyncedPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('external_url', models.URLField(blank=True, max_length=1000)),
                ('space_key', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('content_md', models.TextField()),
                ('checksum', models.CharField(max_length=64)),
                ('last_synced_at', models.DateTimeField()),
                ('last_score', models.FloatField(blank=True, help_text='Most recent scoring-phase probability (0.0–1.0).', null=True)),
                ('extraction_checksum', models.CharField(blank=True, default='', help_text='Checksum at time of last AI extraction. Differs from checksum when page has changed since extraction.', max_length=64)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_pages', to='connectors.connectorcredential')),
            ],
            options={
                'db_table': 'synced_page',
            },
        ),
        migrations.CreateModel(
            name='CandidateSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='connectors.capturecandidate')),
                ('synced_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_sources', to='connectors.syncedpage')),
            ],
            options={
                'db_table': 'candidate_source',
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pages_scanned', models.PositiveIntegerField(default=0)),
                ('pages_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='connectors.connectorcredential')),
            ],
            options={
                'db_table': 'sync_job',
            },
        ),
        migrations.AddIndex(
            model_name='connectorcredential',
            index=models.Index(fields=['workspace', 'provider', 'status'], name='idx_cred_ws_prov_status'),
        ),
        migrations.AddConstraint(
            model_name='connectorcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'expired', 'error'])), fields=('workspace', 'provider'), name='uq_credential_workspace_provider_active'),
        ),
        migrations.AddIndex(
            model_name='capturecandidate',
            index=models.Index(fields=['credential', 'status', '-created_at'], name='idx_cand_cred_status_created'),
        ),
        migrations.AddConstraint(
            model_name='capturecandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'dismissed'), _negated=True), fields=('credential', 'slug'), name='uq_candidate_credential_slug_active'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['credential', '-created_at'], name='idx_extjob_cred_created'),
        ),
        migrations.AddIndex(
            model_name='syncedpage',
            index=models.Index(fields=['credential', 'space_key'], name='idx_syncedpage_cred_space'),
        ),
        migrations.AddIndex(
            model_name='syncedpage',
            index=models.Index(fields=['credential', '-last_synced_at'], name='idx_syncedpage_cred_synced'),
        ),
        migrations.AddConstraint(
            model_name='syncedpage',
            constraint=models.UniqueConstraint(fields=('credential', 'external_id'), name='uq_synced_page_credential_external_id'),
        ),
        migrations.AddConstraint(
            model_name='candidatesource',
            constraint=models.UniqueConstraint(fields=('candidate', 'synced_page'), name='uq_candidate_source'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['credential', '-created_at'], name='idx_syncjob_credential_created'),
        ),
    ]
