# Generated by Django 5.1.15 on 2026-04-16 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='McpConnectionScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('workspace', 'Workspace'), ('team', 'Team'), ('department', 'Department')], default='workspace', max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_scope', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='mcp_connection_scopes', to='orgs.department')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connection_scopes', to='orgs.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_scopes', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connection_scopes', to='orgs.workspace')),
            ],
            options={
                'db_table': 'mcp_connection_scope',
                'constraints': [models.UniqueConstraint(fields=('application', 'user', 'workspace'), name='uq_mcp_scope_app_user_ws')],
            },
        ),
    ]
