# Generated by Django 5.1.15 on 2026-04-26 06:04

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0000_create_vector_extension'),
        ('orgs', '0004_rename_process_to_skill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('department', 'Department'), ('team', 'Team'), ('workspace', 'Workspace')], default='department', max_length=20)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='orgs.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_skills', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_skills', to='orgs.department')),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='SkillVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('content_md', models.TextField()),
                ('frontmatter_yaml', models.TextField(blank=True, default='')),
                ('change_summary', models.CharField(blank=True, default='', max_length=500)),
                ('koinoflow_metadata', models.JSONField(blank=True, default=dict)),
                ('authored_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_versions', to=settings.AUTH_USER_MODEL)),
                ('reverted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revert_children', to='skills.skillversion')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='skills.skill')),
            ],
            options={
                'db_table': 'skill_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='SkillDiscoveryEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('embedding_model', models.CharField(max_length=100)),
                ('embedding_dimensions', models.PositiveSmallIntegerField(default=768)),
                ('content_hash', models.CharField(max_length=64)),
                ('indexed_text', models.TextField()),
                ('indexed_at', models.DateTimeField()),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_embedding', to='skills.skillversion')),
            ],
            options={
                'db_table': 'skill_discovery_embedding',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='skills.skillversion'),
        ),
        migrations.CreateModel(
            name='VersionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=500)),
                ('content', models.TextField(default='')),
                ('content_bytes', models.BinaryField(blank=True, default=b'')),
                ('file_type', models.CharField(choices=[('python', 'Python'), ('markdown', 'Markdown'), ('html', 'Html'), ('yaml', 'Yaml'), ('json', 'Json'), ('javascript', 'Javascript'), ('typescript', 'Typescript'), ('shell', 'Shell'), ('image', 'Image'), ('pdf', 'Pdf'), ('binary', 'Binary'), ('text', 'Text'), ('other', 'Other')], default='text', max_length=50)),
                ('mime_type', models.CharField(blank=True, default='text/plain', max_length=100)),
                ('encoding', models.CharField(blank=True, default='utf-8', max_length=20)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='skills.skillversion')),
            ],
            options={
                'db_table': 'version_file',
            },
        ),
        migrations.AddIndex(
            model_name='skillversion',
            index=models.Index(fields=['skill', '-version_number'], name='idx_version_latest'),
        ),
        migrations.AddConstraint(
            model_name='skillversion',
            constraint=models.UniqueConstraint(fields=('skill', 'version_number'), name='uq_version_skill_number'),
        ),
        migrations.AddIndex(
            model_name='skilldiscoveryembedding',
            index=models.Index(fields=['embedding_model', 'embedding_dimensions'], name='idx_skill_disc_model_dims'),
        ),
        migrations.AddIndex(
            model_name='skilldiscoveryembedding',
            index=models.Index(fields=['content_hash'], name='idx_skill_disc_hash'),
        ),
        migrations.AddIndex(
            model_name='skilldiscoveryembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_skill_disc_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['department', 'status'], name='idx_skill_dept_status'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['status', '-updated_at'], name='idx_skill_status_updated'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['slug'], name='idx_skill_slug'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['-updated_at'], name='idx_skill_updated_at'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'description'], name='idx_skill_search_trgm', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(condition=models.Q(('visibility__in', ['team', 'workspace'])), fields=['visibility'], name='idx_skill_visibility'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('department', 'slug'), name='uq_skill_dept_slug'),
        ),
        migrations.AddConstraint(
            model_name='versionfile',
            constraint=models.UniqueConstraint(fields=('version', 'path'), name='uq_version_file_path'),
        ),
    ]
