# Generated by Cursor on 2026-04-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="execution_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SkillExecutionSpec",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "runtime",
                    models.CharField(
                        choices=[("python", "Python")],
                        default="python",
                        max_length=20,
                    ),
                ),
                (
                    "latency_class",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("interactive", "Interactive"),
                            ("async", "Async"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("entrypoint_path", models.CharField(default="run.py", max_length=500)),
                ("input_schema", models.JSONField(blank=True, default=dict)),
                ("output_schema", models.JSONField(blank=True, default=dict)),
                ("secrets_scope", models.CharField(default="department", max_length=50)),
                (
                    "network_policy",
                    models.CharField(
                        choices=[
                            ("egress_allowlist", "Egress allowlist"),
                            ("none", "No network"),
                        ],
                        default="egress_allowlist",
                        max_length=50,
                    ),
                ),
                ("allowed_egress", models.JSONField(blank=True, default=list)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("memory_mb", models.PositiveIntegerField(default=512)),
                ("max_output_bytes_inline", models.PositiveIntegerField(default=32768)),
                ("max_runs_per_day", models.PositiveIntegerField(default=100)),
                ("max_concurrent_runs", models.PositiveIntegerField(default=1)),
                (
                    "skill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_spec",
                        to="skills.skill",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_specs",
                        to="skills.skillversion",
                    ),
                ),
            ],
            options={
                "db_table": "skill_execution_spec",
            },
        ),
        migrations.CreateModel(
            name="SkillExecutionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caller_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("agent", "Agent"),
                            ("api_key", "API key"),
                            ("oauth", "OAuth"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending approval"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("inputs", models.JSONField(blank=True, default=dict)),
                ("input_hash", models.CharField(max_length=64)),
                ("output", models.JSONField(blank=True, null=True)),
                ("output_uri", models.CharField(blank=True, default="", max_length=1000)),
                ("logs_uri", models.CharField(blank=True, default="", max_length=1000)),
                ("error_message", models.TextField(blank=True, default="")),
                ("external_job_name", models.CharField(blank=True, default="", max_length=255)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("resource_usage", models.JSONField(blank=True, default=dict)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skill_execution_runs",
                        to="agents.agent",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_skill_execution_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skill_execution_runs",
                        to="orgs.department",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_runs",
                        to="skills.skill",
                    ),
                ),
                (
                    "spec",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="skills.skillexecutionspec",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skill_execution_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_runs",
                        to="skills.skillversion",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_execution_runs",
                        to="orgs.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "skill_execution_run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillExecutionQuotaCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day", models.DateField()),
                ("run_count", models.PositiveIntegerField(default=0)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_quota_counters",
                        to="skills.skill",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_execution_quota_counters",
                        to="orgs.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "skill_execution_quota_counter",
            },
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                condition=models.Q(("execution_enabled", True)),
                fields=["execution_enabled"],
                name="idx_skill_exec_enabled",
            ),
        ),
        migrations.AddIndex(
            model_name="skillexecutionspec",
            index=models.Index(fields=["skill"], name="idx_skill_exec_spec_skill"),
        ),
        migrations.AddIndex(
            model_name="skillexecutionspec",
            index=models.Index(fields=["version"], name="idx_skill_exec_spec_version"),
        ),
        migrations.AddIndex(
            model_name="skillexecutionrun",
            index=models.Index(fields=["workspace", "-created_at"], name="idx_exec_run_ws_created"),
        ),
        migrations.AddIndex(
            model_name="skillexecutionrun",
            index=models.Index(fields=["skill", "-created_at"], name="idx_exec_run_skill_created"),
        ),
        migrations.AddIndex(
            model_name="skillexecutionrun",
            index=models.Index(fields=["status", "-created_at"], name="idx_exec_run_status_created"),
        ),
        migrations.AddIndex(
            model_name="skillexecutionrun",
            index=models.Index(fields=["agent", "-created_at"], name="idx_exec_run_agent_created"),
        ),
        migrations.AddIndex(
            model_name="skillexecutionrun",
            index=models.Index(fields=["user", "-created_at"], name="idx_exec_run_user_created"),
        ),
        migrations.AddIndex(
            model_name="skillexecutionquotacounter",
            index=models.Index(fields=["workspace", "day"], name="idx_exec_quota_ws_day"),
        ),
        migrations.AddIndex(
            model_name="skillexecutionquotacounter",
            index=models.Index(fields=["skill", "day"], name="idx_exec_quota_skill_day"),
        ),
        migrations.AddConstraint(
            model_name="skillexecutionquotacounter",
            constraint=models.UniqueConstraint(
                fields=("workspace", "skill", "day"),
                name="uq_exec_quota_ws_skill_day",
            ),
        ),
    ]
