# Generated by Cursor on 2026-04-29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_department_secret_scope(apps, schema_editor):
    SkillExecutionSpec = apps.get_model("skills", "SkillExecutionSpec")
    SkillExecutionSpec.objects.filter(secrets_scope="department").update(secrets_scope="workspace")


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0001_initial"),
        ("skills", "0002_skill_execution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(migrate_department_secret_scope, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="skillexecutionspec",
            name="secrets_scope",
            field=models.CharField(
                choices=[
                    ("workspace", "Workspace"),
                    ("user", "User"),
                    ("platform", "Platform"),
                ],
                default="workspace",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="skillexecutionrun",
            name="secrets_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SkillSecretDeclaration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Secret names must look like environment variable names "
                                    "(e.g. OPENAI_API_KEY)."
                                ),
                                regex="^[A-Z][A-Z0-9_]{0,63}$",
                            )
                        ],
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("user", "User"),
                            ("platform", "Platform"),
                        ],
                        default="workspace",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_refs",
                        to="skills.skillexecutionspec",
                    ),
                ),
            ],
            options={"db_table": "skill_secret_declaration"},
        ),
        migrations.CreateModel(
            name="SkillSecretValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Secret names must look like environment variable names "
                                    "(e.g. OPENAI_API_KEY)."
                                ),
                                regex="^[A-Z][A-Z0-9_]{0,63}$",
                            )
                        ],
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("user", "User"),
                            ("platform", "Platform"),
                        ],
                        default="workspace",
                        max_length=20,
                    ),
                ),
                ("wrapped_dek", models.BinaryField(default=b"")),
                ("ciphertext", models.BinaryField(default=b"")),
                ("kms_key_version", models.CharField(blank=True, default="", max_length=255)),
                (
                    "last_set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="set_skill_secret_values",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_values",
                        to="skills.skill",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_secret_values",
                        to="orgs.workspace",
                    ),
                ),
            ],
            options={"db_table": "skill_secret_value"},
        ),
        migrations.CreateModel(
            name="SkillSecretAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Secret names must look like environment variable names "
                                    "(e.g. OPENAI_API_KEY)."
                                ),
                                regex="^[A-Z][A-Z0-9_]{0,63}$",
                            )
                        ],
                    ),
                ),
                ("granted", models.BooleanField(default=False)),
                ("failure_reason", models.CharField(blank=True, default="", max_length=64)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_access_logs",
                        to="skills.skillexecutionrun",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_access_logs",
                        to="skills.skill",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_secret_access_logs",
                        to="orgs.workspace",
                    ),
                ),
            ],
            options={"db_table": "skill_secret_access_log"},
        ),
        migrations.AddConstraint(
            model_name="skillsecretdeclaration",
            constraint=models.UniqueConstraint(
                fields=("spec", "name"),
                name="uq_skill_secret_decl_spec_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="skillsecretvalue",
            constraint=models.UniqueConstraint(
                fields=("skill", "workspace", "name", "scope"),
                name="uq_skill_secret_value_scope",
            ),
        ),
        migrations.AddIndex(
            model_name="skillsecretdeclaration",
            index=models.Index(fields=["spec"], name="idx_secret_decl_spec"),
        ),
        migrations.AddIndex(
            model_name="skillsecretdeclaration",
            index=models.Index(fields=["name"], name="idx_secret_decl_name"),
        ),
        migrations.AddIndex(
            model_name="skillsecretvalue",
            index=models.Index(fields=["skill", "workspace"], name="idx_secret_value_skill_ws"),
        ),
        migrations.AddIndex(
            model_name="skillsecretvalue",
            index=models.Index(fields=["name"], name="idx_secret_value_name"),
        ),
        migrations.AddIndex(
            model_name="skillsecretaccesslog",
            index=models.Index(fields=["run"], name="idx_secret_log_run"),
        ),
        migrations.AddIndex(
            model_name="skillsecretaccesslog",
            index=models.Index(fields=["workspace", "-created_at"], name="idx_secret_log_ws_created"),
        ),
        migrations.AddIndex(
            model_name="skillsecretaccesslog",
            index=models.Index(fields=["skill", "-created_at"], name="idx_secret_log_skill_created"),
        ),
    ]
