# Generated by Django 5.1.15 on 2026-05-03 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0008_coresettings_sandbox_min_role"),
        ("skills", "0005_skilldiscoveryembedding_indexed_text_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("skill_generation", "Skill generation"),
                            ("file_edit", "File edit"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to="orgs.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "ai_usage_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "created_at"], name="ai_usage_ws_created"
                    ),
                    models.Index(
                        fields=["workspace", "usage_type", "created_at"],
                        name="ai_usage_ws_type_created",
                    ),
                ],
            },
        ),
    ]
