# Generated by Django 5.1.15 on 2026-04-15 18:14

import django.db.migrations.operations.special
import django.db.models.deletion
import uuid
from django.db import migrations, models


SLUG_TO_TITLE = {
    "claude_code": "Claude Code",
    "claude_desktop": "Claude Desktop",
    "cursor": "Cursor",
    "windsurf": "Windsurf Editor",
    "zed": "Zed Editor",
    "copilot": "GitHub Copilot CLI",
    "cline": "Cline",
    "chatgpt": "ChatGPT",
    "gemini_cli": "Gemini CLI",
    "codex": "OpenAI Codex",
    "vscode": "Visual Studio Code",
    "mcp": "MCP",
    "unknown": "Unknown",
    "web": "Web",
    "api": "REST API",
}

CLIENT_NAME_TO_TITLE = {
    "@librechat/api-client": "LibreChat",
    "@n8n/n8n-nodes-langchain.mcpClientTool": "N8N MCP Client",
    "Alpic": "Alpic Playground",
    "amp-mcp-client": "AmpCode",
    "antigravity-client": "Google Antigravity",
    "apify-mcp-client": "Apify MCP Client",
    "arcade": "Arcade",
    "ChatGPT": "ChatGPT",
    "Cherry Studio": "Cherry Studio",
    "claude-ai": "Claude.ai",
    "claude-code": "Claude Code",
    "Cline": "Cline",
    "Codex": "OpenAI Codex",
    "codex-mcp-client": "OpenAI Codex",
    "com.raycast.macos": "Raycast",
    "continue-cli-client": "Continue CLI Client",
    "crush": "Crush",
    "cursor-vscode": "Cursor",
    "dust-mcp-client": "Dust",
    "factory-cli": "Factory CLI",
    "gemini-cli-mcp-client": "Gemini CLI",
    "gitguardian": "GitGuardian",
    "github-copilot-developer": "GitHub Copilot CLI",
    "Glama": "Glama",
    "goose": "Goose",
    "Jan-Streamable-Client": "Jan AI",
    "JetBrains-IU-copilot-intellij": "JetBrains AI Assistant",
    "JetBrains-JBC-copilot-intellij": "JetBrains AI Assistant with GitHub Copilot",
    "Kilo-Code": "Kilo Code",
    "lobehub-mcp-client": "LobeHub",
    "make-app-mcp-client": "Make MCP Client",
    "Mistral": "Mistral AI: Le Chat",
    "opencode": "Opencode",
    "Postman-Client": "Postman",
    "Q-DEV-CLI": "Amazon Q Developer CLI",
    "Roo-Code": "Roo Code",
    "Visual Studio Code": "Visual Studio Code",
    "Visual-Studio-Code": "Visual Studio Code",
    "Windsurf": "Windsurf Editor",
    "windsurf-client": "Windsurf Editor",
    "Xcode-copilot-xcode": "GitHub Copilot for Xcode",
    "Zed": "Zed Editor",
}


def convert_client_types(apps, schema_editor):
    UsageEvent = apps.get_model("usage", "UsageEvent")
    to_update = []
    for event in UsageEvent.objects.filter(client_type__in=SLUG_TO_TITLE):
        event.client_type = SLUG_TO_TITLE[event.client_type]
        to_update.append(event)
    if to_update:
        UsageEvent.objects.bulk_update(to_update, ["client_type"])


def _client_name_from_id(client_id: str) -> str:
    if client_id in CLIENT_NAME_TO_TITLE:
        return client_id
    if "/" not in client_id:
        return client_id

    candidate, _version = client_id.rsplit("/", 1)
    if candidate in CLIENT_NAME_TO_TITLE:
        return candidate
    return client_id


def fix_mcp_client_types(apps, schema_editor):
    UsageEvent = apps.get_model("usage", "UsageEvent")
    to_update = []

    for event in UsageEvent.objects.filter(client_type="MCP").exclude(client_id__exact=""):
        client_name = _client_name_from_id(event.client_id)
        new_client_type = CLIENT_NAME_TO_TITLE.get(client_name)
        if new_client_type:
            event.client_type = new_client_type
            to_update.append(event)

    if to_update:
        UsageEvent.objects.bulk_update(to_update, ["client_type"])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('client_id', models.CharField(default='unknown', max_length=255)),
                ('client_type', models.CharField(default='unknown', max_length=100)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='skills.skill')),
                ('tool_name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'usage_event',
                'ordering': ['-called_at'],
                'indexes': [models.Index(fields=['process', '-called_at'], name='usage_event_process_fff70b_idx'), models.Index(fields=['called_at'], name='usage_event_called__78ac61_idx'), models.Index(fields=['process', 'client_type'], name='idx_usage_process_client_type')],
            },
        ),
        migrations.RunPython(
            code=convert_client_types,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=fix_mcp_client_types,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='client_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
