# Generated by Django 5.1.15 on 2026-04-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usageevent',
            name='usage_event_process_fff70b_idx',
        ),
        migrations.RemoveIndex(
            model_name='usageevent',
            name='idx_usage_process_client_type',
        ),
        migrations.RenameField(
            model_name='usageevent',
            old_name='process',
            new_name='skill',
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['skill', '-called_at'], name='usage_event_skill_i_85de7d_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['skill', 'client_type'], name='idx_usage_skill_client_type'),
        ),
    ]
