# Generated by Django 5.1.15 on 2026-04-15 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'workspace',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_departments', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='orgs.team')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='orgs.workspace'),
        ),
        migrations.CreateModel(
            name='ProcessAuditRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_days', models.PositiveIntegerField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_rules', to='orgs.workspace')),
            ],
            options={
                'db_table': 'process_audit_rule',
            },
        ),
        migrations.CreateModel(
            name='PendingInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('team_manager', 'Team Manager'), ('member', 'Member')], max_length=20)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('departments', models.ManyToManyField(blank=True, to='orgs.department')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='orgs.workspace')),
            ],
            options={
                'db_table': 'pending_invitation',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('team_manager', 'Team Manager'), ('member', 'Member')], default='member', max_length=20)),
                ('departments', models.ManyToManyField(blank=True, related_name='department_memberships', to='orgs.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships', to='orgs.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='orgs.workspace')),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.CreateModel(
            name='CoreSlug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('workspace', 'Workspace'), ('team', 'Team'), ('department', 'Department')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('slug', models.SlugField(max_length=100)),
                ('scope_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_slugs', to='orgs.team')),
                ('scope_workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_slugs', to='orgs.workspace')),
            ],
            options={
                'db_table': 'core_slug',
            },
        ),
        migrations.CreateModel(
            name='CoreSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('require_review_before_publish', models.BooleanField(default=None, null=True)),
                ('enable_version_history', models.BooleanField(default=None, null=True)),
                ('enable_api_access', models.BooleanField(default=None, null=True)),
                ('require_change_summary', models.BooleanField(default=None, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='orgs.department')),
                ('process_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings', to='orgs.processauditrule')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='orgs.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='orgs.workspace')),
            ],
            options={
                'db_table': 'core_settings',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('key_prefix', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('team_manager', 'Team Manager'), ('member', 'Member')], default='admin', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='api_key_departments', to='orgs.department')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='orgs.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='orgs.workspace')),
            ],
            options={
                'db_table': 'api_key',
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['team', 'name'], name='idx_department_team_name'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['workspace', 'name'], name='idx_team_ws_name'),
        ),
        migrations.AddIndex(
            model_name='pendinginvitation',
            index=models.Index(fields=['workspace', 'status'], name='idx_invitation_ws_status'),
        ),
        migrations.AddConstraint(
            model_name='pendinginvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('workspace', 'email'), name='uq_pending_invite_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['workspace', 'role'], name='idx_membership_ws_role'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'workspace'), name='uq_membership_user_workspace'),
        ),
        migrations.AddIndex(
            model_name='coreslug',
            index=models.Index(fields=['entity_type', 'slug'], name='idx_coreslug_type_slug'),
        ),
        migrations.AddIndex(
            model_name='coreslug',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_coreslug_entity_lookup'),
        ),
        migrations.AddIndex(
            model_name='coreslug',
            index=models.Index(fields=['entity_id'], name='idx_coreslug_entity_id'),
        ),
        migrations.AddConstraint(
            model_name='coreslug',
            constraint=models.UniqueConstraint(fields=('entity_type', 'entity_id'), name='uq_coreslug_entity'),
        ),
        migrations.AddConstraint(
            model_name='coreslug',
            constraint=models.UniqueConstraint(condition=models.Q(('entity_type', 'workspace')), fields=('slug',), name='uq_slug_workspace'),
        ),
        migrations.AddConstraint(
            model_name='coreslug',
            constraint=models.UniqueConstraint(condition=models.Q(('entity_type', 'team')), fields=('scope_workspace', 'slug'), name='uq_slug_team'),
        ),
        migrations.AddConstraint(
            model_name='coreslug',
            constraint=models.UniqueConstraint(condition=models.Q(('entity_type', 'department')), fields=('scope_team', 'slug'), name='uq_slug_dept'),
        ),
        migrations.AddConstraint(
            model_name='coreslug',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entity_type', 'workspace'), ('scope_team__isnull', True), ('scope_workspace__isnull', True)), models.Q(('entity_type', 'team'), ('scope_team__isnull', True), ('scope_workspace__isnull', False)), models.Q(('entity_type', 'department'), ('scope_team__isnull', False), ('scope_workspace__isnull', True)), _connector='OR'), name='ck_coreslug_scope_fks'),
        ),
        migrations.AddIndex(
            model_name='coresettings',
            index=models.Index(fields=['workspace'], name='idx_settings_workspace'),
        ),
        migrations.AddIndex(
            model_name='coresettings',
            index=models.Index(fields=['workspace', 'team'], name='idx_settings_ws_team'),
        ),
        migrations.AddIndex(
            model_name='coresettings',
            index=models.Index(fields=['workspace', 'team', 'department'], name='idx_settings_ws_team_dept'),
        ),
        migrations.AddConstraint(
            model_name='coresettings',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True), ('team__isnull', True)), fields=('workspace',), name='uq_settings_workspace'),
        ),
        migrations.AddConstraint(
            model_name='coresettings',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True), ('team__isnull', False)), fields=('workspace', 'team'), name='uq_settings_team'),
        ),
        migrations.AddConstraint(
            model_name='coresettings',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('workspace', 'team', 'department'), name='uq_settings_department'),
        ),
        migrations.AddConstraint(
            model_name='coresettings',
            constraint=models.CheckConstraint(condition=models.Q(('department__isnull', True), ('team__isnull', False), _connector='OR'), name='ck_settings_dept_requires_team'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_hash', 'is_active'], name='idx_apikey_hash_active'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['workspace', '-created_at'], name='idx_apikey_ws_created'),
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'feature_flag',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceFeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_assignments', to='orgs.featureflag')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='orgs.workspace')),
            ],
            options={
                'db_table': 'workspace_feature_flag',
                'indexes': [models.Index(fields=['workspace'], name='idx_wff_workspace')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'flag'), name='uq_workspace_feature_flag')],
            },
        ),
    ]
