# Generated by Django 5.1.15 on 2026-04-17 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StalenessAlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_days', models.PositiveIntegerField()),
                ('notify_admins', models.BooleanField(default=True)),
                ('notify_team_managers', models.BooleanField(default=False)),
                ('notify_process_owner', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staleness_alert_rules', to='orgs.workspace')),
            ],
            options={
                'db_table': 'staleness_alert_rule',
            },
        ),
        migrations.AddField(
            model_name='coresettings',
            name='staleness_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings', to='orgs.stalenessalertrule'),
        ),
    ]
