# Generated by Django 5.1.15 on 2026-04-28 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_index_agents_system_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_created_at', models.DateTimeField(blank=True, null=True)),
                ('team_created_at', models.DateTimeField(blank=True, null=True)),
                ('department_created_at', models.DateTimeField(blank=True, null=True)),
                ('skill_created_at', models.DateTimeField(blank=True, null=True)),
                ('mcp_connected_at', models.DateTimeField(blank=True, null=True)),
                ('skill_read_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='orgs.workspace')),
            ],
            options={
                'db_table': 'workspace_onboarding',
            },
        ),
        migrations.CreateModel(
            name='AdminOnboardingPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_preferences', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_preferences', to='orgs.workspace')),
            ],
            options={
                'db_table': 'admin_onboarding_preference',
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='uq_onboarding_pref_ws_user')],
            },
        ),
    ]
